version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mediarr-sonarr-anime_sonarr-anime_1
      APP_PORT: 8990
      PROXY_AUTH_WHITELIST: "/api/*"

  sonarr-anime:
    image: linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: unless-stopped