services:
  app_proxy:
    environment:
      APP_HOST: mediarr-radarr_server_1
      APP_PORT: 7878
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home:/home
    restart: on-failure