services:
  app_proxy:
    environment:
      APP_HOST: mediarr-whisparr_server_1
      APP_PORT: 6969
      PROXY_AUTH_WHITELIST: "/api/*"
      
  server:
    image: ghcr.io/hotio/whisparr:v3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${UMBREL_ROOT}/home/Downloads:/Downloads
      - ${UMBREL_ROOT}/home/Media:/Media
    restart: unless-stopped