services:
  app_proxy:
    environment:
      APP_HOST: mediarr-sabnzbd_web_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api*"

  web:
    image: linuxserver/sabnzbd:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads:/Downloads
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=ffmpeg
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
