services:
  app_proxy:
    environment:
      APP_HOST: mediarr-dockhand_dockhand_1
      APP_PORT: 3000

  dockhand:
    image: fnsys/dockhand:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data:/app/data
      - ${UMBREL_ROOT}:/umbrel
    restart: unless-stopped