version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: mediarr-emby_server_1
      APP_PORT: 8096
      PROXY_AUTH_ADD: "false"

  server:
    image: linuxserver/emby:latest
    environment:
      TZ: Europe/Berlin
      UID: 1000
      GID: 1000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config:rw
      - ${UMBREL_ROOT}/data/storage/Media:/Media
