services:
  app_proxy:
    environment:
      APP_HOST: mediarr-jellyfin_server_1
      APP_PORT: 8096
      PROXY_AUTH_ADD: "false"

  server:
    image: linuxserver/jellyfin:latest
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/:/Media
      - ${UMBREL_ROOT}/home/Downloads/:/Downloads
    ports:
      # Service auto-discovery
      - 7359:7359/udp
