services:
  app_proxy:
    environment:
      APP_HOST: mediarr-wizarr_server_1
      APP_PORT: 5690
      
  server:
    image: ghcr.io/wizarrrr/wizarr:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - DISABLE_BUILTIN_AUTH=false
      - TZ=UTC
