services:
  app_proxy:
    environment:
      APP_HOST: mediarr-prowlarr_server_1
      APP_PORT: 9696
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads:/Downloads
    restart: on-failure

  indexer_proxy:
    image: flaresolverr/flaresolverr:v3.4.6@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
    restart: on-failure