version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: mediarr-nzbdav-rclone_nzbdav-rclone_1
      PROXY_AUTH_WHITELIST: "/api/*"

  nzbdav-rclone:
    image: nzbdav/nzbdav:0.5.4
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/config/rclone.conf:/config/rclone/rclone.conf
      - ${UMBREL_ROOT}/data/storage/downloads/nzbdav:/downloads/nzbdav:rshared
    environment:
      # Change these IDs to match your Docker user that you got from above
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on: mediarr-nzbdav_nzbdav_1
      conditions: service_healthy
      restart: true
    command: >
    mount nzbdav: ${UMBREL_ROOT}/data/storage/downloads/nzbdav
      --uid=1000
      --gid=1000
      --allow-other
      --links
      --use-cookies
      --vfs-cache-mode=full
      --vfs-cache-max-size=20G
      --vfs-cache-max-age=24h
      --buffer-size=64M
      --vfs-read-ahead=512M
      --dir-cache-time=20s