services:
  app_proxy:
    environment:
      APP_HOST: mediarr-stashdb_server_1
      APP_PORT: 9999
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: stashapp/stash:latest
    environment:
      - PUID=1000
      - PGID=1000
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/config:/root/.stash
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/generated:/generated
      - ${APP_DATA_DIR}/metadata:/metadata
      - ${APP_DATA_DIR}/cache:/cache
      - ${APP_DATA_DIR}/blobs:/blobs
      - ${UMBREL_ROOT}/home/Downloads:/Downloads
      - ${UMBREL_ROOT}/home/Media:/Media
    restart: unless-stopped