services:
  app_proxy:
    environment:
      APP_HOST: mediarr-sonarr-anime_server_1
      APP_PORT: 8989
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home:/Downloads
    restart: on-failure